// Generated by CoffeeScript 1.8.0
var KeyCode;

KeyCode = (function() {
  function KeyCode() {}

  KeyCode.BACKSPACE = 8;

  KeyCode.TAB = 9;

  KeyCode.ENTER = 13;

  KeyCode.SHIFT = 16;

  KeyCode.CTRL = 17;

  KeyCode.ALT = 18;

  KeyCode.PAUSE = 19;

  KeyCode.CAPS_LOCK = 20;

  KeyCode.ESCAPE = 27;

  KeyCode.SPACE = 32;

  KeyCode.PAGE_UP = 33;

  KeyCode.PAGE_DOWN = 34;

  KeyCode.END = 35;

  KeyCode.HOME = 36;

  KeyCode.LEFT_ARROW = 37;

  KeyCode.UP_ARROW = 38;

  KeyCode.RIGHT_ARROW = 39;

  KeyCode.DOWN_ARROW = 40;

  KeyCode.INSERT = 45;

  KeyCode.DELETE = 46;

  KeyCode.KEY_0 = 48;

  KeyCode.KEY_1 = 49;

  KeyCode.KEY_2 = 50;

  KeyCode.KEY_3 = 51;

  KeyCode.KEY_4 = 52;

  KeyCode.KEY_5 = 53;

  KeyCode.KEY_6 = 54;

  KeyCode.KEY_7 = 55;

  KeyCode.KEY_8 = 56;

  KeyCode.KEY_9 = 57;

  KeyCode.KEY_A = 65;

  KeyCode.KEY_B = 66;

  KeyCode.KEY_C = 67;

  KeyCode.KEY_D = 68;

  KeyCode.KEY_E = 69;

  KeyCode.KEY_F = 70;

  KeyCode.KEY_G = 71;

  KeyCode.KEY_H = 72;

  KeyCode.KEY_I = 73;

  KeyCode.KEY_J = 74;

  KeyCode.KEY_K = 75;

  KeyCode.KEY_L = 76;

  KeyCode.KEY_M = 77;

  KeyCode.KEY_N = 78;

  KeyCode.KEY_O = 79;

  KeyCode.KEY_P = 80;

  KeyCode.KEY_Q = 81;

  KeyCode.KEY_R = 82;

  KeyCode.KEY_S = 83;

  KeyCode.KEY_T = 84;

  KeyCode.KEY_U = 85;

  KeyCode.KEY_V = 86;

  KeyCode.KEY_W = 87;

  KeyCode.KEY_X = 88;

  KeyCode.KEY_Y = 89;

  KeyCode.KEY_Z = 90;

  KeyCode.LEFT_META = 91;

  KeyCode.RIGHT_META = 92;

  KeyCode.SELECT = 93;

  KeyCode.NUMPAD_0 = 96;

  KeyCode.NUMPAD_1 = 97;

  KeyCode.NUMPAD_2 = 98;

  KeyCode.NUMPAD_3 = 99;

  KeyCode.NUMPAD_4 = 100;

  KeyCode.NUMPAD_5 = 101;

  KeyCode.NUMPAD_6 = 102;

  KeyCode.NUMPAD_7 = 103;

  KeyCode.NUMPAD_8 = 104;

  KeyCode.NUMPAD_9 = 105;

  KeyCode.MULTIPLY = 106;

  KeyCode.ADD = 107;

  KeyCode.SUBTRACT = 109;

  KeyCode.DECIMAL = 110;

  KeyCode.DIVIDE = 111;

  KeyCode.F1 = 112;

  KeyCode.F2 = 113;

  KeyCode.F3 = 114;

  KeyCode.F4 = 115;

  KeyCode.F5 = 116;

  KeyCode.F6 = 117;

  KeyCode.F7 = 118;

  KeyCode.F8 = 119;

  KeyCode.F9 = 120;

  KeyCode.F10 = 121;

  KeyCode.F11 = 122;

  KeyCode.F12 = 123;

  KeyCode.NUM_LOCK = 144;

  KeyCode.SCROLL_LOCK = 145;

  KeyCode.SEMICOLON = 186;

  KeyCode.EQUALS = 187;

  KeyCode.COMMA = 188;

  KeyCode.DASH = 189;

  KeyCode.PERIOD = 190;

  KeyCode.FORWARD_SLASH = 191;

  KeyCode.GRAVE_ACCENT = 192;

  KeyCode.OPEN_BRACKET = 219;

  KeyCode.BACK_SLASH = 220;

  KeyCode.CLOSE_BRACKET = 221;

  KeyCode.SINGLE_QUOTE = 222;

  return KeyCode;

})();

//# sourceMappingURL=KeyCode.js.map
